[vectorfield.circular]
src = [0, 0]
dst = [6, 2]
xlim = [0, 6]
ylim = [-1, 6]
travel_stw = 10

[vectorfield.fourvortices]
src = [0, 0]
dst = [6, 2]
xlim = [0, 6]
ylim = [-1, 6]
travel_stw = 1

[vectorfield.swirlys]
src = [0, 0]
dst = [6, 5]
xlim = [0, 6]
ylim = [-1, 6]
travel_time = 30

[vectorfield.techy]
src = [0.8660254037844386, 0.5]  # [cos(pi/6), sin(pi/6)]
dst = [0, 1]
xlim = [-1, 1]
ylim = [-0.5, 1.5]
travel_stw = 1

[land]
water_level = [1.1, 0.9, 0.8, 0.7]
resolution = [5]
random_seed = [2]
penalty = [100]

[optimizer.cmaes]
popsize = [200, 500, 1000]
L = [64, 128, 256]
K = [3, 6, 9]
sigma0 = [1, 3, 5]
tolfun = [1e-6]
