DICT_PORTS = {
    "CAVAN": {"lat": 48.50, "lon": -124.82, "city": "Vancouver", "country": "Canada"},
    "CNSHA": {"lat": 31.28, "lon": 121.98, "city": "Shanghai", "country": "China"},
    "DEHAM": {"lat": 53.99, "lon": 8.63, "city": "Hamburg", "country": "Germany"},
    "EGHRG": {
        "lat": 27.66,
        "lon": 33.88,
        "city": "Suez",
        "country": "Egypt",
        "canal": "Suez",
        "ocean": "Indian",
    },
    "EGPSD": {
        "lat": 31.53,
        "lon": 32.32,
        "city": "Suez",
        "country": "Egypt",
        "canal": "Suez",
        "ocean": "Mediterranean",
    },
    "ESALG": {"lat": 36.07, "lon": -5.38, "city": "Algeciras", "country": "Spain"},
    "FRLEH": {"lat": 49.49, "lon": 0.06, "city": "Le Havre", "country": "France"},
    "JPTYO": {
        "lat": 34.8,
        "lon": 140.0,
        "city": "Tokyo/Yokohama",
        "country": "Japan",
    },
    "LKCMB": {"lat": 6.93, "lon": 79.79, "city": "Colombo", "country": "Sri Lanka"},
    "PABLB": {
        "lat": 8.89,
        "lon": -79.53,
        "city": "Balboa",
        "country": "Panama",
        "canal": "Panama",
        "ocean": "Pacific",
    },
    "PAONX": {
        "lat": 9.43,
        "lon": -79.92,
        "city": "Colon",
        "country": "Panama",
        "canal": "Panama",
        "ocean": "Atlantic",
    },
    "PECLL": {
        "lat": -12.19,
        "lon": -77.23,
        "city": "Callao",
        "country": "Peru",
    },
    "ESSDR": {
        "lat": 43.6,
        "lon": -4.0,
        "city": "Santander",
        "country": "Spain",
    },
    "USLAX": {
        "lat": 34.4,
        "lon": -121.0,
        "city": "Los Angeles",
        "country": "United States",
    },
    "USHOU": {
        "lat": 29.30,
        "lon": -94.63,
        "city": "Houston",
        "country": "United States",
    },
    "USLBH": {
        "lat": 33.73,
        "lon": -118.17,
        "city": "Long Beach",
        "country": "United States",
    },
    "USNYC": {
        "lat": 40.53,
        "lon": -73.80,
        "city": "New York",
        "country": "United States",
    },
    "USSAV": {
        "lat": 31.99,
        "lon": -80.76,
        "city": "Savannah",
        "country": "United States",
    },
    "MYKUL": {
        "lat": 2.968,
        "lon": 100.899,
        "city": "Kuala Lumpur",
        "country": "Malaysia",
    },
}
DICT_BENCHMARKS = {
    "route_days": 10,
    "benchmarks": {
        "DEHAM-USNYC": {"date_start": "2023-01-01T00:00:00"},
        "USNYC-DEHAM": {"date_start": "2023-01-01T00:00:00"},
        "EGHRG-MYKUL": {"date_start": "2023-01-01T00:00:00"},
        "MYKUL-EGHRG": {"date_start": "2023-01-01T00:00:00"},
        "EGPSD-ESALG": {"date_start": "2023-01-01T00:00:00"},
        "ESALG-EGPSD": {"date_start": "2023-01-01T00:00:00"},
        "PABLB-PECLL": {"date_start": "2023-01-01T00:00:00"},
        "PECLL-PABLB": {"date_start": "2023-01-01T00:00:00"},
        "PAONX-USNYC": {"date_start": "2023-01-01T00:00:00"},
        "USNYC-PAONX": {"date_start": "2023-01-01T00:00:00"},
        # SWOPP3
        "ESSDR-USNYC": {"date_start": "2023-01-01T00:00:00"},
        "USLAX-JPTYO": {"date_start": "2023-01-01T00:00:00"},
    },
}
