import numpy as np
import scipy
import searoute as sr

from routetools.wrr_bench.ocean import EARTH_RADIUS, Ocean, beaufort_scale


def searoute_waypoints(
    lat_start: float,
    lon_start: float,
    lat_end: float,
    lon_end: float,
    size: int | None = None,
) -> np.ndarray:
    """
    Compute waypoints between two coordinates using searoute.

    Parameters
    ----------
    lat_start : float
        Latitude of the starting point.
    lon_start : float
        Longitude of the starting point.
    lat_end : float
        Latitude of the ending point.
    lon_end : float
        Longitude of the ending point.
    size : Optional[int], optional
        Number of waypoints to be generated.
        This value can be:
        - None: The number of waypoints will be defined by searoutes
        - Lower than the number of waypoints generated by searoutes:
        The number of waypoints
        will be the given value, keeping points from searoutes.
        - Higher than the number of waypoints generated by searoutes:
        The number of waypoints
        will be the given value, using all searoutes' waypoints
        and interpolating new ones.

    Returns
    -------
    np.ndarray
        Array containing the waypoints for the given lat, lon coordinates.
    """
    origin = [lon_start, lat_start]
    destination = [lon_end, lat_end]

    coordinates_dict = sr.searoute(origin, destination, append_orig_dest=True)

    coords = np.array(coordinates_dict["geometry"]["coordinates"])
    lats, lons = coords[:, 1], coords[:, 0]

    if size is None:
        # When the user does not specify the size, we use searoutes' length.
        # This will skip the while loops shown below
        size = len(lats)
    else:
        # When the user specifies a size, we need to adjust the number of waypoints
        # In order to do so, we compute the distance between waypoints
        d = distance_from_points(
            lats[:-1], lons[:-1], lats[1:], lons[1:], land_penalization=0
        )

    # One of the following loops will happen when the user specifies a size
    # different from the number of waypoints generated by searoutes
    # In both scenarios, our goal is to keep as many searoutes' points as possible
    # while ensuring a relatively even distribution of waypoints (equidistant)

    # When the required size is lower than the number of waypoints,
    # we remove points starting from the shortest segment
    while len(lats) > size:
        # Find the shortest segment
        idx = np.argmin(d)
        if idx == 0:
            # If it is the first segment, remove the second point
            idx = 1
        elif idx == (len(d) - 1):
            # If it is the last segment, remove the second to last point
            idx = idx
        elif d[idx - 1] > d[idx + 1]:
            # If its in the middle, remove the point closest to
            # the segment with the shortest distance
            idx = idx + 1
        else:
            idx = idx
        # Drop the point
        lats = np.delete(lats, idx)
        lons = np.delete(lons, idx)
        # Readjust the distances
        d = distance_from_points(
            lats[:-1], lons[:-1], lats[1:], lons[1:], land_penalization=0
        )

    # When the required size is higher than the number of waypoints,
    # we interpolate points starting from the longest segment
    while len(lats) < size:
        # Find the longest segment
        idx = np.argmax(d)
        # Interpolate the middle coordinate
        lats = np.insert(lats, idx + 1, np.mean(lats[idx : idx + 2]))
        lons = np.insert(lons, idx + 1, np.mean(lons[idx : idx + 2]))
        # Readjust the distances
        d = distance_from_points(
            lats[:-1], lons[:-1], lats[1:], lons[1:], land_penalization=0
        )

    return np.array([lats, lons]).T


def auto_bounding_box(
    lat_start: float,
    lon_start: float,
    lat_end: float,
    lon_end: float,
    padding: float = 5,
) -> tuple[float]:
    """
    Compute the bounding box for a route between two points.

    It queries searoute to obtain waypoints and then expands the min/max
    coordinates by the requested padding.

    Parameters
    ----------
    lat_start : float
        Latitude of the starting point.
    lon_start : float
        Longitude of the starting point.
    lat_end : float
        Latitude of the ending point.
    lon_end : float
        Longitude of the ending point.
    padding : float
        Padding to be added to the bounding box in degrees, by default 5.

    Returns
    -------
    tuple[float]
        Tuple containing the minimum latitude, minimum longitude, maximum
        latitude and maximum longitude.
    """
    waypoints = searoute_waypoints(lat_start, lon_start, lat_end, lon_end)
    lats = waypoints[:, 0]
    lons = waypoints[:, 1]

    min_lat = min(lats) - padding
    max_lat = max(lats) + padding
    min_lon = min(lons) - padding
    max_lon = max(lons) + padding

    return (min_lat, min_lon, max_lat, max_lon)


def unit_vector(lat: np.array, lon: np.array) -> np.array:
    """
    Compute the 3D unit vector for latitude/longitude points.

    Parameters
    ----------
    lat : np.array
        Array containing the latitude of the points.
    lon : np.array
        Array containing the longitude of the points.

    Returns
    -------
    np.array
        Array containing the unit vector of the given lat, lon coordinates.
    """
    lat, lon = np.deg2rad(lat), np.deg2rad(lon)
    x = np.cos(lat) * np.cos(lon)
    y = np.cos(lat) * np.sin(lon)
    z = np.sin(lat)

    return np.array([x, y, z])


def distance_from_points(
    lat_start: np.array,
    lon_start: np.array,
    lat_end: np.array,
    lon_end: np.array,
    ocean_data: Ocean = None,
    radius: float = EARTH_RADIUS,
    land_penalization: float = 0,
) -> np.array:
    """
    Compute distances in meters between pairs of coordinates.

    ``ocean_data`` can override the sphere radius. If ``radius`` is ``None``,
    distances are computed in the plane.

    Parameters
    ----------
    lat_start : np.array
        Array containing the latitude of the starting points.
    lon_start : np.array
        Array containing the longitude of the starting points.
    lat_end : np.array
        Array containing the latitude of the ending points.
    lon_end : np.array
        Array containing the longitude of the ending points.
    radius : float
        Radius of the sphere. Default value is the Earth's radius in meters.
    land_penalization : float
        Value to be added to the distance when the route touches land, in meters,
        by default 0.

    Returns
    -------
    np.array
        Array containing the distances in meters between the two points.
    """
    radius = radius if ocean_data is None else ocean_data.radius

    if radius is None:
        # Compute Euclidean distance
        dist = np.sqrt((lat_end - lat_start) ** 2 + (lon_end - lon_start) ** 2)
    else:
        unit_vector_start = unit_vector(lat_start, lon_start)
        unit_vector_end = unit_vector(lat_end, lon_end)

        # Compute the angle between the two unit vectors
        dot_product = np.sum(unit_vector_start * unit_vector_end, axis=0)
        angle = np.arccos(dot_product)  # radians
        dist = radius * angle

    # Checks if the union between start and end crosses land,
    # and if it does, we add extra distance to penalize it
    if (land_penalization != 0) and (ocean_data is not None):
        for i in range(lat_start.shape[0]):
            lats = np.array([lat_start[i], lat_end[i]])
            lons = np.array([lon_start[i], lon_end[i]])
            is_land = ocean_data.get_land_edge(lats, lons).max()
            dist[i] += is_land * land_penalization

    return dist


def angle_from_points(
    lat_start: np.array,
    lon_start: np.array,
    lat_end: np.array,
    lon_end: np.array,
    ocean_data: Ocean = None,
    radius: float = EARTH_RADIUS,
) -> np.array:
    """
    Compute azimuth angles (degrees) between coordinate pairs.

    Parameters
    ----------
    lat_start : np.array
        Array containing the latitude of the starting points in degrees.
    lon_start : np.array
        Array containing the longitude of the starting points in degrees.
    lat_end : np.array
        Array containing the latitude of the ending points in degrees.
    lon_end : np.array
        Array containing the longitude of the ending points in degrees.
    ocean_data : Ocean
        Ocean object containing the ocean data.
    radius : float
        Radius of the sphere. Default value is the Earth's radius in meters.

    Returns
    -------
    np.array
        Array containing the angles in degrees between the two points.
    """
    radius = radius if ocean_data is None else ocean_data.radius

    if radius is None:
        # Compute the angle in a plane
        return np.rad2deg(np.arctan2(lon_end - lon_start, lat_end - lat_start))
    else:
        # Compute the angle in a sphere
        x1, y1, z1 = unit_vector(lat_start, lon_start)
        x2, y2, z2 = unit_vector(lat_end, lon_end)

        return np.rad2deg(
            np.arctan2(
                -x2 * y1 + x1 * y2, -(x1 * x2 + y1 * y2) * z1 + (x1**2 + y1**2) * z2
            )
        )


def module_angle_from_components(v: np.array, u: np.array) -> tuple[np.array]:
    """
    Compute the module and the angle in degrees (with respect to latitude=azimuth).

    Compute the module and the angle of the given vector.

    Parameters
    ----------
    v : np.array
        Array containing the v (latitude) component of the vector.
    u : np.array
        Array containing the u (longitude) component of the vector.

    Returns
    -------
    Tuple[np.array]
        Tuple containing the module and the angle of the vector.
    """
    module = np.sqrt(v**2 + u**2)
    angle = np.rad2deg(np.arctan2(u, v))

    return module, angle


def components_from_module_angle(module: np.array, angle: np.array) -> tuple[np.array]:
    """
    Compute the v and u components of the given vector.

    Parameters
    ----------
    module : np.array
        Array containing the module of the vector.
    angle : np.array
        Array containing the angle in degrees (with respect to latitude).

    Returns
    -------
    Tuple[np.array]
        Tuple containing the v and u components of the vector.
    """
    angle = np.deg2rad(angle)
    v = module * np.cos(angle)  # When parallel to latitude: 0º -> cos(0º) = 1
    u = module * np.sin(angle)  # When perpendicular to latitude: 90º -> sin(90º) = 1

    return v, u


def compute_currents_projection(
    lat_start: np.ndarray | float,
    lon_start: np.ndarray | float,
    lat_end: np.ndarray | float,
    lon_end: np.ndarray | float,
    timestamps: np.ndarray | float,
    ocean_data: Ocean,
) -> tuple[np.ndarray]:
    """
    Compute currents components perpendicular and parallel to the ship direction.

    Parameters
    ----------
    lat_start : Union[np.array, float]
        Array containing the latitude of the starting points in degrees.
    lon_start : Union[np.array, float]
        Array containing the longitude of the starting points in degrees.
    lat_end : Union[np.array, float]
        Array containing the latitude of the ending points in degrees.
    lon_end : Union[np.array, float]
        Array containing the longitude of the ending points in degrees.
    timestamps : Union[np.array, float]
        Array containing the timestamps of the starting and ending points. In
        format datetime as astring
    ocean_data: Ocean
        Ocean object containing the ocean data.


    Returns
    -------
    Tuple[np.array]
        Tuple containing the v and u components of the vector.
    """
    # Compute the distance between the two points
    angle = angle_from_points(
        lat_start, lon_start, lat_end, lon_end, ocean_data=ocean_data
    )

    current_v, current_u = ocean_data.get_currents(lat_start, lon_start, timestamps)
    current_module, current_angle = module_angle_from_components(current_v, current_u)

    current_angle_proj = current_angle - angle

    # u is the components perpendicular to the ship direction over ground
    # v is the components parallel to the ship direction over ground
    current_v_proj, current_u_proj = components_from_module_angle(
        current_module, current_angle_proj
    )

    return current_v_proj, current_u_proj


def _coefficient_direction_reduction(
    wave_incidence_angle: np.ndarray, beaufort: np.ndarray
) -> np.ndarray:
    """Interpolated from Ship Resistance and Propulsion by Anthony F. Molland.

    Also uses Townsin-Kwon's paper on speed loss due to added resistance in
    wind and waves.

    Parameters
    ----------
    wave_incidence_angle : np.ndarray
        Relative angle between ship and incoming waves in degrees.
    beaufort : np.ndarray
        Sliding Beaufort level, converted from wave height

    Returns
    -------
    np.ndarray
        Direction reduction coefficient, C_beta or mu
    """
    rad = np.radians(wave_incidence_angle)
    a = 6 * np.sin(rad / 2) ** (2 / 3) + 2
    r = 1.205 * rad
    b = 0.06 * (1 + (np.sin(r) - np.cos(r))) / (1 + np.sqrt(2))
    c = 2 - 1.6 * np.sin(rad / 2)
    return (c - b * (beaufort - a) ** 2) / 2


def _coefficient_speed_reduction(
    beaufort: np.ndarray,
    displacement: float,
) -> np.ndarray:
    """Speed reduction coefficient (equation 3.65) from Molland.

    This equation gives a ratio of the ship's velocity with respect to the
    beaufort levels.

    Parameters
    ----------
    beaufort : np.ndarray
        Sliding Beaufort level
    displacement : float
        Ship displacement in m^3

    Returns
    -------
    np.ndarray
        speed reduction coefficient, C_u or alpha
    """
    return (0.7 * beaufort + beaufort ** (6.5)) / (22 * displacement ** (2 / 3))


def _correction_factor(froude_number: np.ndarray, coef_block: float) -> np.ndarray:
    """Taken from Table 3.12 of Ship Resistance and Propulsion by Anthony F. Molland.

    The range of block coefficient is from 0.55 - 0.85.

    Parameters
    ----------
    froude_number : np.ndarray
        froude number as list of float
    coef_block : float
        block coefficient as list of float

    Returns
    -------
    np.ndarray
        correction factor, C_u or alpha

    Raises
    ------
    ValueError
        Block coefficient too low, less than 0.55
    ValueError
        Block coefficient too high, greater than 0.85
    """
    if coef_block < 0.55:
        raise ValueError("Block coefficient too low")
    elif coef_block == 0.55:
        # Normal
        a, b, c = 1.7, 1.4, 7.4
    elif coef_block <= 0.6:
        # Normal
        a, b, c = 2.2, 2.5, 9.7
    elif coef_block <= 0.65:
        # Normal
        a, b, c = 2.6, 3.7, 11.6
    elif coef_block <= 0.7:
        # Normal
        a, b, c = 3.1, 5.3, 12.4
    elif coef_block <= 0.75:
        # Normal or laden
        a, b, c = 2.4, 10.6, 9.5
    elif coef_block <= 0.8:
        # Normal or laden
        a, b, c = 2.6, 13.1, 15.1
    elif coef_block <= 0.85:
        # Normal or laden
        a, b, c = 3.1, 18.7, 28
    else:
        raise ValueError("Block coefficient too high")
    return a - b * froude_number - c * froude_number**2


def _speed_loss_involuntary(
    beaufort: np.ndarray,
    wave_incidence_angle: np.ndarray,
    vel_ship: float | np.ndarray,
    coef_block: float = 0.6,
    length: float = 220,
    displacement: float = 36500,
) -> np.ndarray:
    """
    Speed loss as a percentage between 0% to 100%.

    Only valid for large ships (displacement > 100,000 m3). Typical
    reductions should be between 0 to 30.


    Parameters
    ----------
    beaufort : np.ndarray
        Sliding scale of Beaufort levels
    wave_incidence_angle : np.ndarray
        Relative angle between ship and incoming waves in degrees
    vel_ship : Union[float,np.array]
        Ship velocity over water.
        If it is a float, it will be considered constant.
    coef_block : float, optional
        Block coefficient of the ship, by default 0.6
    length : float, optional
        Length of the ship, in m, by default 220
    displacement : float, optional
        Displacement of the ship, in m^3, by default 36500

    Returns
    -------
    np.ndarray
        Speed reduction coefficient taking into account of all coefficients.
    """
    if isinstance(vel_ship, float):
        vel_ship = np.full(wave_incidence_angle.shape, vel_ship)

    c_beta = _coefficient_direction_reduction(wave_incidence_angle, beaufort)
    c_u = _coefficient_speed_reduction(beaufort, displacement)

    # Computes froude number, given the ship's velocity and length,
    # g = 9.81 m/s^2, the gravitational acceleration
    froude_number = vel_ship / (length * 9.81) ** 0.5
    alpha = _correction_factor(froude_number, coef_block)
    return np.clip(c_beta * c_u * alpha, a_min=0, a_max=100)


def _cost_function_linalg(
    lat: np.ndarray,
    lon: np.ndarray,
    ts: np.ndarray,
    angle: np.ndarray,
    distance: np.ndarray,
    vel_ship: float | np.ndarray,
    ocean_data: Ocean,
    clip_p: float = 0.2,
) -> np.ndarray:
    """
    Auxiliary function for compute_times_linalg.

    Parameters
    ----------
    lat : np.ndarray
        Latitudes coordinates, it can be multiple routes.
    lon : np.ndarray
        Longitude coordinates, it can be multiple routes.
    ts : np.ndarray
        Timestamps, it can be multiple routes.
    angle : np.ndarray
        Angle of the ship
    distance : np.ndarray
        Distance between the two points
    vel_ship : Union[float, np.ndarray]
        Ship velocity in m/s.
    ocean_data : Ocean
        Ocean object.
    clip_p : float
        Percentage to set the minimum of the velocity over ground, by default 0.2

    Returns
    -------
    np.ndarray
        Costs per segment
    """
    if not isinstance(vel_ship, np.ndarray):
        vel_ship = np.full(lat.shape, vel_ship)

    assert (
        lat.shape
        == lon.shape
        == ts.shape
        == vel_ship.shape
        == angle.shape
        == distance.shape
    ), f"""
    Input variables shapes do not match
    lat: {lat.shape}
    lon: {lon.shape}
    ts: {ts.shape}
    vel_ship: {vel_ship.shape}
    angle: {angle.shape}
    distance: {distance.shape}
    """

    original_shape = lat.shape

    lat = lat.flatten()
    lon = lon.flatten()
    ts = ts.flatten()
    vel_ship = vel_ship.flatten()
    angle = angle.flatten()
    distance = distance.flatten()

    current_v, current_u = ocean_data.get_currents(lat, lon, ts)
    cur_mod, cur_ang = module_angle_from_components(current_v, current_u)

    # Angle of the current projected on the line of movement over ground
    cur_ang_proj = cur_ang - angle
    # This angle is with respect to X-axis, however the rest of the functions
    # refer to Y-axis. To compensate, in the next function we will assume (u, v)
    # instead of the usual (v, u)

    wave_height, wave_angle = ocean_data.get_waves(lat, lon, ts)

    # Computes wave incidence angle
    wia = np.mod(np.abs(angle - wave_angle), 360)
    wave_incidence_angle = np.minimum(wia, 360 - wia)
    # Computes beaufort and speed loss percentage
    beaufort_levels = beaufort_scale(
        wave_height=wave_height, asfloat=True, beaufort_max=8
    )
    speed_loss = _speed_loss_involuntary(
        beaufort=beaufort_levels,
        wave_incidence_angle=wave_incidence_angle,
        vel_ship=vel_ship,
    )

    # Apply speed loss
    vel_ship = vel_ship * (100 - speed_loss) / 100

    # u is the components perpendicular to the ship direction over ground
    # v is the components parallel to the ship direction over ground
    cur_u_proj, cur_v_proj = components_from_module_angle(cur_mod, cur_ang_proj)
    # Clip the perpendicular velocity to avoid negative values
    # We assume the vessel will increase its power to compensate
    vel_v2 = np.clip(vel_ship**2 - cur_v_proj**2, a_min=0, a_max=None)
    vel_ground = cur_u_proj + np.sqrt(vel_v2)
    # When wave heights are too high, the velocity over ground can turn negative
    # which is physically not possible. To avoid this, we clip the values to a
    # minimum of 20% of the vel_ship
    vel_clip = max(clip_p * vel_ship.min(), 1e-6)
    vel_ground = np.clip(vel_ground, a_min=vel_clip, a_max=None)

    return np.reshape(distance / vel_ground, original_shape)


def compute_times_linalg(
    lat_start: np.ndarray | float,
    lon_start: np.ndarray | float,
    lat_end: np.ndarray | float,
    lon_end: np.ndarray | float,
    timestamps: np.ndarray | float,
    vel_ship: float | np.ndarray,
    ocean_data: Ocean,
    land_penalization: float = 0,
) -> np.ndarray:
    """
    Compute the time series for the given lat, lon coordinates and timestamps.

    This uses the ships trajectory and its normal vector as a basis, apply a
    change of basis to the vectorfield, compute the effect of the vectorfield
    to the ship, and compute the time it takes to travel the path specified.

    Parameters
    ----------
    lat_start : np.array
        Array containing the latitude of the starting points.
    lon_start : np.array
        Array containing the longitude of the starting points.
    lat_end : np.array
        Array containing the latitude of the ending points.
    lon_end : np.array
        Array containing the longitude of the ending points.
    timestamps : np.array
        Array containing the timestamps.
    vel_ship : Union[float, np.ndarray]
        Ship velocity in m/s.
    ocean_data : Ocean
        Ocean object.
    land_penalization : float
        Value to be added to the distance when the route touches land, in meters,
        by default 0.

    Returns
    -------
    np.array
        Array containing the time in seconds for the given lat, lon coordinates.
    """
    lat_start = np.atleast_1d(lat_start)
    lon_start = np.atleast_1d(lon_start)
    lat_end = np.atleast_1d(lat_end)
    lon_end = np.atleast_1d(lon_end)
    timestamps = np.atleast_1d(timestamps)

    # Compute the distance between the two points
    distance = distance_from_points(
        lat_start,
        lon_start,
        lat_end,
        lon_end,
        ocean_data=ocean_data,
        land_penalization=land_penalization,
    )
    # Compute the distance between the two points
    angle = angle_from_points(
        lat_start, lon_start, lat_end, lon_end, ocean_data=ocean_data
    )

    # Compute the time
    l1 = _cost_function_linalg(
        lat_start,
        lon_start,
        timestamps,
        angle=angle,
        distance=distance,
        vel_ship=vel_ship,
        ocean_data=ocean_data,
    )
    l2 = _cost_function_linalg(
        lat_end,
        lon_end,
        timestamps,
        angle=angle,
        distance=distance,
        vel_ship=vel_ship,
        ocean_data=ocean_data,
    )
    # Takes the average of the cost from the start points and end points
    ld = (l1 + l2) / 2
    return ld


def _cost_function_integral(
    lat: np.ndarray,
    lon: np.ndarray,
    dist_lat: np.ndarray,
    dist_lon: np.ndarray,
    ts: np.ndarray,
    vel_ship: float | np.ndarray,
    ocean_data: Ocean,
) -> np.ndarray:
    """Update cost function from the paper above.

    This helper is nested in the function to access variables in
    `compute_times_alpha`.

    Parameters
    ----------
    lat : np.ndarray
        latitudes coordinates
    lon : np.ndarray
        longitude coordinates
    dist_lat : np.ndarray
        latitude component of ship's velocity over ground
    dist_lon : np.ndarray
        longitude component of ship's velocity over ground
    ts : np.ndarray
        timestamps
    vel_ship : Union[float,np.array]
        Ship velocity in m/s, can be a float or an array.
    ocean_data : Ocean
        Ocean object.

    Returns
    -------
    np.ndarray
        costs per segment
    """
    v_cur, u_cur = ocean_data.get_currents(lat, lon, ts)

    # alpha gives a ratio of the ship's velocity with respect
    # to the currents
    alpha = vel_ship**2 - (u_cur**2 + v_cur**2)
    cost = np.sqrt(
        1 / alpha * (dist_lon**2 + dist_lat**2)
        + 1 / (alpha**2) * (u_cur * dist_lon + v_cur * dist_lat) ** 2
    ) - 1 / alpha * (u_cur * dist_lon + v_cur * dist_lat)
    # TODO: Include the effect of waves
    return cost


def compute_times_integral(
    lat_start: np.ndarray | float,
    lon_start: np.ndarray | float,
    lat_end: np.ndarray | float,
    lon_end: np.ndarray | float,
    timestamps: np.ndarray | float,
    vel_ship: float | np.ndarray,
    ocean_data: Ocean,
    land_penalization: float = 0,
) -> np.ndarray:
    """Compute the cost function for the given lat, lon coordinates and timestamps.

    This uses the numerical integration of the cost function, which is given
    by the paper below. The cost function is computed by looking at the
    Finsler Metric over our manifold.

    This is done to ensure all cost functions in the project are
    consistent.

    Reference: https://arxiv.org/abs/2109.05559

    lat_start, lon_start, lat_end, lon_end, and timestamps must all have the
    same length

    The cost function takes half from the start points and half from the end
    points.

    Parameters
    ----------
    lat_start : np.array
        Array containing the latitude of the starting points.
    lon_start : np.array
        Array containing the longitude of the starting points.
    lat_end : np.array
        Array containing the latitude of the ending points.
    lon_end : np.array
        Array containing the longitude of the ending points.
    timestamps : np.array
        Array containing the timestamps.
    vel_ship : Union[float, np.ndarray]
        Ship velocity in m/s.
    ocean_data : Ocean
        Ocean object.

    Returns
    -------
    np.array
        Array containing the time in seconds for the given lat, lon coordinates.
    """
    lat_start = np.atleast_1d(lat_start)
    lon_start = np.atleast_1d(lon_start)
    lat_end = np.atleast_1d(lat_end)
    lon_end = np.atleast_1d(lon_end)
    timestamps = np.atleast_1d(timestamps)

    dist = distance_from_points(
        lat_start,
        lon_start,
        lat_end,
        lon_end,
        ocean_data=ocean_data,
        land_penalization=land_penalization,
    )

    ang = angle_from_points(
        lat_start, lon_start, lat_end, lon_end, ocean_data=ocean_data
    )

    dist_lat, dist_lon = components_from_module_angle(dist, ang)

    l1 = _cost_function_integral(
        lat_start,
        lon_start,
        dist_lat,
        dist_lon,
        timestamps,
        vel_ship=vel_ship,
        ocean_data=ocean_data,
    )
    l2 = _cost_function_integral(
        lat_end,
        lon_end,
        dist_lat,
        dist_lon,
        timestamps,
        vel_ship=vel_ship,
        ocean_data=ocean_data,
    )
    # Takes the average of the cost from the start points and end points
    ld = (l1 + l2) / 2
    return ld


def velocity_over_ground(
    vel_ship: float | np.ndarray,
    lat_start: np.ndarray | float,
    lon_start: np.ndarray | float,
    lat_end: np.ndarray | float,
    lon_end: np.ndarray | float,
    timestamps: np.ndarray | float,
    ocean_data: Ocean,
):
    """Return ship velocity over ground component (u) for segments.

    Non-functional helper: projects currents and computes ground-speed u
    component required by some solvers.
    """
    current_v_proj, current_u_proj = compute_currents_projection(
        lat_start, lon_start, lat_end, lon_end, timestamps, ocean_data
    )
    return current_u_proj + np.sqrt(vel_ship**2 - current_v_proj**2)


def compute_times_given_coordinates_and_start(
    latitudes: np.array,
    longitudes: np.array,
    ts_start: np.array,
    vel_ship: float | np.ndarray,
    ocean_data: Ocean,
    land_penalization: float = 0,
) -> np.array:
    """
    Compute the time series for the given lat, lon coordinates and timestamps.

    Parameters
    ----------
    latitudes : np.array
        Array containing the latitude of the route points.
        It shape can be (N_routes, N_points) or (N_points,)
    longitudes : np.array
        Array containing the longitude of the starting points.
        It shape can be (N_routes, N_points) or (N_points,)
    ts_start : np.array
        Starting timestamp.
        It shape can be (N_routes,) or (1,)
    vel_ship : Union[float, np.ndarray]
        Ship velocity in m/s.
    ocean_data : Ocean
        Ocean object.
    land_penalization : float
        Time to be assigned when land is reached, in seconds,
        by default 0.

    Returns
    -------
    np.array
        Array containing the time in seconds for the given lat, lon coordinates.
    """
    latitudes = np.atleast_2d(latitudes)
    longitudes = np.atleast_2d(longitudes)
    ts_start = np.atleast_1d(ts_start)

    # Turn vel_ship into array if its not one
    if type(vel_ship) is not np.ndarray:
        vel_ship = np.full(latitudes.shape, vel_ship)
    else:
        vel_ship = np.atleast_2d(vel_ship)

    time_now = ts_start
    ts: list[np.datetime64] = [time_now]

    for i in range(latitudes.shape[1] - 1):
        lat_start = latitudes[:, i]
        lon_start = longitudes[:, i]
        lat_end = latitudes[:, i + 1]
        lon_end = longitudes[:, i + 1]

        time = compute_times_linalg(
            lat_start,
            lon_start,
            lat_end,
            lon_end,
            time_now,
            vel_ship[:, i],
            ocean_data,
            land_penalization=land_penalization,
        )

        # When NaN or negative is returned, it means that the
        # currents are higher than the ship velocity
        # This can happen when the ship is too slow
        time = np.nan_to_num(time, nan=land_penalization)
        time[time.astype(float) < 0] = land_penalization

        time_now = time_now + np.array(time * 1e6, dtype="timedelta64[us]")

        ts.append(time_now)

    ts = np.array(ts).swapaxes(0, 1)

    return ts


def route_segments_distance(
    lat: np.array,
    lon: np.array,
    ocean_data: Ocean = None,
    land_penalization: float = 0,
) -> float:
    """Compute the distance of each segment of a route.

    Parameters
    ----------
    lat : np.array
        Latitudes of the route.
    lon : np.array
        Longitudes of the route
    ocean_data : Ocean
        Ocean object containing the ocean data.
    land_penalization : float
        Value to be added to the distance when the route touches land, by default 0.

    Returns
    -------
    float
        Distance of the route.
    """
    num_routes = lat.shape[0]
    lat_start = lat[:, :-1].flatten()
    lon_start = lon[:, :-1].flatten()
    lat_end = lat[:, 1:].flatten()
    lon_end = lon[:, 1:].flatten()
    dist = np.reshape(
        distance_from_points(
            lat_start=lat_start,
            lon_start=lon_start,
            lat_end=lat_end,
            lon_end=lon_end,
            ocean_data=ocean_data,
            land_penalization=land_penalization,
        ),
        (num_routes, -1),
    )

    return dist


def route_distance(
    lat: np.array,
    lon: np.array,
    ocean_data: Ocean = None,
    land_penalization: float = 0,
) -> float:
    """Compute the distance of a route given by a sequence of latitudes and longitudes.

    Parameters
    ----------
    lat : np.array
        Latitudes of the route.
    lon : np.array
        Longitudes of the route
    ocean_data : Ocean
        Ocean object containing the ocean data.
    land_penalization : float
        Value to be added to the distance when the route touches land, by default 0.

    Returns
    -------
    float
        Distance of the route.
    """
    dist = np.sum(
        route_segments_distance(
            lat=lat,
            lon=lon,
            ocean_data=ocean_data,
            land_penalization=land_penalization,
        ),
        axis=1,
    )

    return dist


def even_reparametrization(
    curve: np.array,
    cost: callable,
    n_points: int = None,
    cost_per_segment: float = None,
    n_iter: int = 5,
    verbose: bool = True,
) -> np.array:
    """Reparameterize a polyline so that the cost is the same on each segment.

    Given a polyline and a cost function, reparameterize the polyline so that
    the cost becomes the same on each segment (either a fixed number of
    points or a fixed cost between points).

    Parameters
    ----------
    curve :  np.ndarray
        A polyline with shape P x 2
    cost : callable
        a function taking a polyline (shape P x 2) and returning a
        vector of costs (shape P-1)
    n_points : int
        Number of desired points for the new polyline. Default is None. Pass either this
          or `cost_per_segment`
    cost_per_segment : float
        The target cost of each segment. If None (default), `n_points` points will be
        generated
    n_iter : int, optional
        Number of iterations, by default 5
    verbose : bool, optional
        Print the standard deviation of the cost at each iteration

    Returns
    -------
        A new polyline approximating the original,
        and an array with the cost of each segment
    """

    def resample_trajectory(t, y):
        """Evaluate points on a trajectory parameterized as a polyline.

        Parameters
        ----------
        t: np.ndarray
            Evaluation points (vector of shape K), all between 0 and 1
        y: np.ndarray
            Segment endpoints, with shape P x 2

        Returns
        -------
            Natch of resampled y (matrix of shape K x 2)
        """
        assert t.ndim == 1
        assert y.ndim == 2

        def do_slice(t, y):
            n_points = y.shape[0]
            prevt = np.linspace(0, 1, n_points)
            newt = scipy.interpolate.interp1d(
                prevt, y, assume_sorted=True, fill_value="extrapolate"
            )(t)
            return newt

        return np.concatenate(
            [do_slice(t, y[:, sl])[:, None] for sl in range(y.shape[1])], axis=1
        )

    def even_resample(t: np.array, y: np.array, n_points: int, cost_per_segment: float):
        """Resample t so that points on the y axis are evenly spaced.

        Given a function t -> y, resample t into P points so that points on
        the y axis are evenly spaced.

        """
        assert t.ndim == 1
        assert y.ndim == 1
        assert t.shape == y.shape

        if n_points is None:
            n_points = int(np.floor((y[-1] - y[0]) / cost_per_segment)) + 2
            newy = np.concatenate(
                [
                    np.linspace(
                        y[0], y[0] + (n_points - 2) * cost_per_segment, (n_points - 1)
                    ),
                    [y[-1]],
                ]
            )
        else:
            newy = np.linspace(y[0], y[-1], n_points)
        newt = scipy.interpolate.interp1d(
            y, t, assume_sorted=True, fill_value="extrapolate"
        )(newy)
        return newt

    assert curve.ndim == 2

    newt = np.linspace(0, 1, curve.shape[0]).T
    newcurve = curve
    for i in range(n_iter):
        current_cost = cost(newcurve)
        if verbose:
            print(f"Iteration {i} | std = {np.std(current_cost)}")
        cumulative_cost = np.concatenate([np.zeros(1), np.cumsum(current_cost)])
        # Get values of t that even out the costs
        newt = even_resample(newt, cumulative_cost, n_points, cost_per_segment)
        # Update the curve with the new t
        newcurve = resample_trajectory(t=newt, y=curve)
        # If the STW is present in the curve, the last value is NaN
        # to indicate the vessel is not moving further.
        # However, due to the interpolation, more than one NaN could appear.
        # Only the last point of the STW should be NaN
        if newcurve.shape[1] == 3:
            # Fill NaNs except the last point of the STW
            newcurve[:-1, 2] = np.nan_to_num(
                newcurve[:-1, 2], nan=np.nanmean(newcurve[:-1, 2])
            )
    return newcurve, cost(newcurve)


def split_route_segments(
    lat: np.ndarray, lon: np.ndarray, threshold: float = 10000, ocean_data: Ocean = None
) -> tuple[np.ndarray, np.ndarray]:
    """
    Ensure that none of the path segments is longer than `threshold`.

    Take a path (in lon/lat units) and make sure that none of its segments
    is longer than `threshold`.
    Distances are computed using the Haversine formula.

    Algorithm: whenever a segment is too long, it is split in two
    by placing a middle point (in lon/lat space).
    This is repeated until all segments are in order.

    Parameters
    ----------
    lat : np.ndarray
        Array of latitude values, in degrees
    lon : np.ndarray
        Array of longitude values, in degrees
    threshold : float, optional
        How long (in meters) should each final segment be, at most.
        By default 10000

    Returns
    -------
    Tuple[np.ndarray, np.ndarray]
        Tuple containing two arrays: latitudes and longitudes
        of the split route segments
    """

    def recursion(
        a_lat: float, a_lon: float, b_lat: float, b_lon: float
    ) -> list[tuple[float, float]]:
        """Recurs the pair of points (a_lat, a_lon), (b_lat, b_lon).

        Create a bigger list until the distance between a and b is less than
        the threshold.

        """
        dist = distance_from_points(
            a_lat, a_lon, b_lat, b_lon, ocean_data=ocean_data, land_penalization=0
        )
        if dist <= threshold:
            return [(a_lat, a_lon), (b_lat, b_lon)]
        # Convert to radians
        a_latr, a_lonr, b_latr, b_lonr = np.deg2rad([a_lat, a_lon, b_lat, b_lon])
        # split the segment in two (accounting for the Earth curvature)
        bx = np.cos(b_latr) * np.cos(b_lonr - a_lonr)
        by = np.cos(b_latr) * np.sin(b_lonr - a_lonr)
        mid_lat = np.arctan2(
            np.sin(a_latr) + np.sin(b_latr),
            np.sqrt((np.cos(a_latr) + bx) ** 2 + by**2),
        )
        mid_lon = a_lonr + np.arctan2(by, np.cos(a_latr) + bx)
        # Convert back to degrees
        mid_lat, mid_lon = np.rad2deg(mid_lat), np.rad2deg(mid_lon)
        return (
            recursion(a_lat, a_lon, mid_lat, mid_lon)
            + recursion(mid_lat, mid_lon, b_lat, b_lon)[1:]
        )

    result_lat = [lat[0]]
    result_lon = [lon[0]]
    # iterate over the pairs of points
    for i in range(1, len(lat)):
        result = recursion(lat[i - 1], lon[i - 1], lat[i], lon[i])[1:]
        result_lat.extend([point[0] for point in result])
        result_lon.extend([point[1] for point in result])
    # return the result as numpy arrays
    return np.array(result_lat), np.array(result_lon)
