name: Pytest

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Validate uv.lock
        # Quick parse check to fail fast if uv.lock is malformed
        run: python tools_parse_uv_lock.py
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.3/install.sh | sh
      - name: Test with pytest
        run: |
          uv sync --dev --frozen
          uv run pytest
